### Create Subsidiary Ledger Account Request
# @name createSubsidiaryLedgerAccount
POST  http://localhost:5000/peoples
Content-Type: application/json
Accept: application/json

## Request Body
{
    "NameEn": "Newton Mitro",
    "DateOfBirth": "1988-03-13",
    "Nid": "",
    "BloodGroup": "B (+ve)",
    "Gender": "Male",
    "Religion": "Christian",
    "Profession": "Service Holder",
    "MaritalStatus": "Married",
    "BirthRegistrationNumber": "123",
    "RegisteredEmail": "newton.mitro@gmail.com",
    "RegisteredMobile": "03132131631",
    "Alive": true,
    "Photo": "",
    "Addresses":[{
        "AddressType": "Present Address",
        "AddressLineOne": "sdfds",
        "AddressLineTwo": "",
        "Country": "Bangladesh",
        "State": "sdfsd",
        "City": "sfsf",
        "Division": "sdfdsf",
        "District": "sfsdf",
        "SubDistrict": "sdfdsf",
        "ZipCode": "sfsdf"
    }],
    "FamilyAndRelatives":[],
    "Educations": [],
    "Trainings":[],
    "EmploymentHistories":[],
    "Attachments": []
}