### Create Person Request
# @name createPerson
POST  http://localhost:5000/peoples
Content-Type: application/json
Accept: application/json

## Request Body
{
  "NameEn": "John Doe",
  "NameBn": null,
  "DateOfBirth": "1996-06-13",
  "Gender": "Male",
  "BloodGroup": "B (+ve)",
  "Religion": "Christian",
  "NID": "123456789",
  "BirthRegistrationNumber": null,
  "MaritalStatus": "Married",
  "ContactNumber": null,
  "MobileNumber": null,
  "PhoneNumber": "123456789",
  "Email": "john@email.com",
  "Profession": "Service Holder",
  "Addresses": [
    {
      "AddressType": "Present Address",
      "AddressLineOne": "sdfds",
      "AddressLineTwo": "",
      "Country": "Bangladesh",
      "State": "sdfsd",
      "City": "sfsf",
      "Division": "sdfdsf",
      "District": "sfsdf",
      "SubDistrict": "sdfdsf",
      "ZipCode": "sfsdf"
    }
  ], 
  "FamilyTree": [
    {
      "NameEn": "Jane Doe",
      "NameBn": "",
      "DateOfBirth": "2000-04-21",
      "NID": "",
      "BloodGroup": "B (+ve)",
      "Gender": "Female",
      "Religion": "Christian",
      "Profession": "Service Holder",
      "MaritalStatus": "Married",
      "BirthRegistrationNumber": "123",
      "ContactNumber": "",
      "MobileNumber": "",
      "PhoneNumber": "",
      "Email": null,
      "Photo": {
        "FileExtension": "jpeg",
        "DocumentTitle": "Photo",
        "Base64StringDocument": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
      },
      "Relationship": "Sister",
      "Status": "Pending"
    }
  ], 
  "Educations": [
    {
      "EducationLevel": "Education Level",
      "EducationDegree": "EducationDegree",
      "InstituteName": "InstituteName",
      "MajorSubject": "MajorSubject",
      "PassingYear": "PassingYear",
      "Grade": "Grade"
    }
  ],
  "Trainings": [
    {
      "CourseTitle": "CourseTitle",
      "InstituteName": "InstituteName",
      "CourseContent": "CourseContent",
      "Result": "",
      "StartDate": "2000-04-21",
      "EndDate": "2000-04-21"
    }
  ],
  "EmploymentHistories": [
    {
      "OrganizationName": "CCCUL",
      "Position": "Software Engineer",
      "Address": "Address",
      "SupervisorName": "SupervisorName",
      "SupervisorDesignation": "SupervisorDesignation",
      "SupervisorPhone": "SupervisorPhone",
      "JobResponsibilities": "JobResponsibilities",
      "Salary": null,
      "StartDate": "2000-04-21",
      "EndDate": null,
      "TillNow": true
    }
  ],
  "Attachments": [
    {
      "FileExtension": "jpeg",
      "DocumentTitle": "Passport",
      "Base64StringDocument": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
    }
  ]
}