### Create Organization Request
# @name createOrganization
POST  http://localhost:5000/organizations
Content-Type: application/json
Accept: application/json

## Request Body
{
  "NameEn": "Bangle Co-operative",
  "NameBn": null,
  "TIN": null,
  "ContactNumber": null,
  "MobileNumber": "01704666666",
  "PhoneNumber": null,
  "Fax":null,
  "Website": null,
  "Email": "bangle.cooperative@email.com",
  "ParentOrganization": null,
  "Addresses": [
    {
      "AddressType": "Present Address",
      "AddressLineOne": "sdfds",
      "AddressLineTwo": "",
      "Country": "Bangladesh",
      "State": "sdfsd",
      "City": "sfsf",
      "Division": "sdfdsf",
      "District": "sfsdf",
      "SubDistrict": "sdfdsf",
      "ZipCode": "sfsdf"
    }
  ],
  "ContactPeoples": [
    {
      "NameEn": "John Doe",
      "NameBn": "",
      "DateOfBirth": "1988-03-13",
      "NID": "",
      "BloodGroup": "B (+ve)",
      "Gender": "Male",
      "Religion": "Christian",
      "Profession": "Service Holder",
      "MaritalStatus": "Married",
      "BirthRegistrationNumber": "123",
      "ContactNumber": "0170455555555",
      "MobileNumber":null,
      "PhoneNumber": null,
      "Email": "john@emal.com"
    }
  ],
  "BankAccounts": [
    {
      "BankName": "ABC Bank",
      "Branch": "Dhaka",
      "RoutingNumber": null,
      "AccountNumber": "123123123",
      "AccountName": "Bangle Co"
    }
  ],
  "Attachments": [
    {
      "FileExtension": "png",
      "DocumentTitle": "Registration Certificate",
      "Base64StringDocument": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
    }
  ]
}