### Login Request
# @name login
POST {{host}}/auth/signup
Content-Type: application/json
Accept: application/json

## Request Body
{
    "name":"Newton Mitro",
    "username": "newtonmitro@gmail.com", 
    "password": "password"
}