### Login Request
# @name login
POST {{host}}/auth/login
Content-Type: application/json
Accept: application/json

## Request Body
{
    "username": "newtonmitro@gmail.com", 
    "password": "password"
}

### Set Token
@refToken = {{login.response.body.refreshToken}}
@token = {{login.response.body.accessToken}}

### Get Authenticated User Request
# @name refreshToken
GET {{host}}/auth/refresh
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{refToken}}


### Get Authenticated User Request
# @name authUser
GET {{host}}/auth/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}



